//home
export const POST_QUESTION_REQUEST = "POST_QUESTION_REQUEST";
export const POST_QUESTION_SUCCESS = "POST_QUESTION_SUCCESS";
export const POST_QUESTION_FAILURE = "POST_QUESTION_FAILURE";
//
//
//
//
//

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAIL = "GET_POSTS_FAIL";

export const POST_ANSWER_REQUEST = "POST_ANSWER_REQUEST";
export const POST_ANSWER_SUCCESS = "POST_ANSWER_SUCCESS";
export const POST_ANSWER_FAIL = "POST_ANSWER_FAIL";

//
export const POST_QUESTION_COMMENT_REQUEST = "POST_QUESTION_COMMENT_REQUEST";
export const POST_QUESTION_COMMENT_SUCCESS = "POST_QUESTION_COMMENT_SUCCESS";
export const POST_QUESTION_COMMENT_FAILURE = "POST_QUESTION_COMMENT_FAILURE";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";

export const VOTE_QUESTION_REQUEST = "VOTE_QUESTION_REQUEST";
export const VOTE_QUESTION_SUCCESS = "VOTE_QUESTION_SUCCESS";
export const VOTE_QUESTION_FAILURE = "VOTE_QUESTION_FAILURE";

export const VOTE_ANSWER_REQUEST = "VOTE_ANSWER_REQUEST";
export const VOTE_ANSWER_SUCCESS = "VOTE_ANSWER_SUCCESS";
export const VOTE_ANSWER_FAILURE = "VOTE_ANSWER_FAILURE";

export const GET_ALLTAGS_REQUEST = "GET_ALLTAGS_REQUEST";
export const GET_ALLTAGS_SUCCESS = "GET_ALLTAGS_SUCCESS";
export const GET_ALLTAGS_FAILURE = "GET_ALLTAGS_FAILURE";

export const GET_SINGLETAG_POSTS_REQUEST = "GET_SINGLETAG_POSTS_REQUEST";
export const GET_SINGLETAG_POSTS_SUCCESS = "GET_SINGLETAG_POSTS_SUCCESS";
export const GET_SINGLETAG_POSTS_FAILURE = "GET_SINGLETAG_POSTS_FAILURE";

export const SUBSCRIBE_TAG_REQUEST = "SUBSCRIBE_TAG_REQUEST";
export const SUBSCRIBE_TAG_SUCCESS = "SUBSCRIBE_TAG_SUCCESS";
export const SUBSCRIBE_TAG_FAILURE = "SUBSCRIBE_TAG_FAILURE";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

export const VIEW_PROFILE_REQUEST = "VIEW_PROFILE_REQUEST";
export const VIEW_PROFILE_SUCCESS = "VIEW_PROFILE_SUCCESS";
export const VIEW_PROFILE_FAILURE = "VIEW_PROFILE_FAILURE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const ADMIN_COUNT_DATA_REQUEST = "ADMIN_COUNT_DATA_REQUEST";
export const ADMIN_COUNT_DATA_SUCCESS = "ADMIN_COUNT_DATA_SUCCESS";
export const ADMIN_COUNT_DATA_FAILURE = "ADMIN_COUNT_DATA_FAILURE";

export const ADMIN_ANALYTICS_DATA_REQUEST = "ADMIN_ANALYTICS_DATA_REQUEST";
export const ADMIN_ANALYTICS_DATA_SUCCESS = "ADMIN_ANALYTICS_DATA_SUCCESS";
export const ADMIN_ANALYTICS_DATA_FAILURE = "ADMIN_ANALYTICS_DATA_FAILURE";
